### ISSUE TITLE
Handle specific async behaviors outside event callbacks

### ISSUE THREAD

**Issue by uriell** [ySnoopyDogy/MenheraBot#110]
Saw your twitter thread, only briefly looked at the code so I may be missing context here but..

Maybe you could move async code that really doesn't have to precede other behaviors, outside of event handlers? When you use async/await for everything inside your event callback you end up delaying the command validation/execution until much later.

An example would be the AFK system, from what I've gathered it manages your nickname on a guild/server and could potentially be ran in parallel with command executions. That way you could also isolate potential AFK-related issues that today would block the command response times or success rates.

A simpler approach would be just not using async/await and allowing the promise that handles AFK to not run synchronously, or maybe isolating the entire responsability of that code outside the event callback (maybe look into enqueueing jobs for another service to handle?).

**Comment by ySnoopyDogy** [comment]
Thank you for that approach. I will remove the await instruction so the event can go without those delays. I put it await there because i was using WebStorm, and it said 'You are ignoring the promise returned here'. But i actually dont use the return. Thanks again for you help. <3
Beijos de luz da Lux
